// Angular/amplify-cognito-auth-demo/src/app/app.component.ts
import {Component} from '@angular/core';
import {Auth, Hub} from 'aws-amplify';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'amplify-cognito-auth-demo';

  constructor() {
  }

  ngOnInit() {
    Hub.listen('auth', ({payload: {event, data}}) => {
      switch (event) {
        case 'signIn':
        case 'cognitoHostedUI':
          Auth.currentAuthenticatedUser().then((userData) => {
            console.log(userData);
          }).catch((error) => {
            console.error(error.message);
          });
          break;
        case 'signOut':
          break;
        case 'signIn_failure':
        case 'cognitoHostedUI_failure':
          console.error('Sign in failure', data);
          break;
      }
    });
  }

  webSignIn() {
    Auth.federatedSignIn();
  }

  signOut() {
    Auth.signOut();
  }
}

<div>
  <button (click)="webSignIn()">Sign-In</button>
</div>

// React/amplify-cognito-auth-demo/src/App.js
import React, {useEffect, useState} from 'react';
import Amplify, {Auth, Hub} from 'aws-amplify';
import './App.css';

Amplify.configure({
    Auth: {
        region: '',
        userPoolId: '',
        userPoolWebClientId: '',
        authenticationFlowType: 'USER_SRP_AUTH',
        oauth: {
            domain: '',
            scope: ['email', 'profile', 'openid'],
            redirectSignIn: 'http://localhost:3000',
            redirectSignOut: 'http://localhost:3000',
            responseType: 'code'
        }
    }
})


function App() {
    const [user, setUser] = useState(null);

    useEffect(() => {
        Hub.listen('auth', ({payload: {event, data}}) => {
            switch (event) {
                case 'signIn':
                case 'cognitoHostedUI':
                    getUser().then(userData => setUser(userData));
                    break;
                case 'signOut':
                    setUser(null);
                    break;
                case 'signIn_failure':
                case 'cognitoHostedUI_failure':
                    console.log('Sign in failure', data);
                    break;
            }
        });

        getUser().then(userData => setUser(userData));
    }, []);

    function getUser() {
        return Auth.currentAuthenticatedUser()
            .then(userData => userData)
            .catch(() => console.log('Not signed in'));
    }

    return (
        <div>
            <p>User: {user ? JSON.stringify(user.username) : 'None'}</p>
            {user ? (
                <button onClick={() => Auth.signOut()}>Sign Out</button>
            ) : (
                <button onClick={() => Auth.federatedSignIn()}>Federated Sign In</button>
            )}
        </div>
    );
}

export default App;
